- name: Deploy SSH Keys
  block:
    - name: Copy SSH Public key
      become: yes
      ansible.builtin.copy:
        src: id_rsa_pihole.pub
        dest: "/home/{{ ansible_user }}/.ssh/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Copy SSH Private Key
      become: yes
      ansible.builtin.copy:
        src: id_rsa_pihole
        dest: "/home/{{ ansible_user }}/.ssh/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
 
- name: Ensure key is not present in authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: absent
    key: "{{ lookup('file', 'id_rsa_pihole.pub') }}"
    key_options: 'command="rsync --server --sender -vlogDtprze.iLsfxC . /etc/pihole/gravity.db",no-port-forwarding,no-pty'

- name: Deploy sync script to any secondaries
  become: yes
  ansible.builtin.template:
    src: pihole-sync.j2
    dest: /usr/local/bin/pihole-sync
    mode: 0555

- name: Add cron job for sync script to any secondaries
  become: yes
  ansible.builtin.cron:
    name: Sync Pihole
    cron_file: pihole-sync
    user: root
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: "/usr/local/bin/pihole-sync && /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ pihole_healthcheck_id }}"
